name: Node.js CI
#name : C'est le nom de ton workflow.

on: [push, pull_request]
# Déclenche le workflow lorsqu'il y a un push ou pull-request

jobs:
  build:
    runs-on: windows-latest
    # Le workflow s'exécute sur windows
    steps:
      - uses: actions/checkout@v4 # Vérifie le code du dépôt
      - name: Use Node.js
        uses: actions/setup-node@v4 # Configure Node.js
        with:
          node-version: "20.x" # On utilise Node.js version 20.x
      - run: npm ci # Installe les dépendances du projet
      - run: npm run build --if-present # Exécute le script de build s'il existe
      - run: npm test # Exécute les tests
